name: megatron_fused_adam
lr: null
weight_decay: 0.01
eps: 1e-08
betas:
  - 0.9
  - 0.999
sched:
  name: WarmupHoldPolicy
  warmup_steps: 1000
  hold_steps: 10000000000000 # Incredibly large value to hold the lr as constant
capturable: True
master_weights: True
max_norm: ${trainer.gradient_clip_val}
